// src/constants/mockData.js (updated with MOCK_ASTROLOGY and GOAL_PROJECTION)
export const FEATURES = [
  { icon: "⚡", title: "AI Growth Engine", desc: "AI powered analysis that identifies your exact growth levers, mistakes, and fastest path to viral content.", badge: "Core" },
  { icon: "📊", title: "Social Analytics", desc: "Deep-dive engagement metrics, growth velocity tracking, and competitive benchmarking across platforms.", badge: "Analytics" },
  { icon: "🔮", title: "Astrology Insights", desc: "Vedic astrology meets content science — discover your lucky posting windows and cosmic growth patterns.", badge: "Unique" },
  { icon: "📅", title: "Daily Action Plan", desc: "Personalized 6-step daily routine generated by AI based on your analytics, goals, and optimal posting times.", badge: "AI" },
];

export const MOCK_PROFILE = {
  platform: "instagram",
  username: "cosmic.creator",
  followers: 284700,
  following: 1243,
  engagement_rate: 4.8,
  total_posts: 312,
  avg_likes: 9800,
  avg_comments: 487,
  top_posts: [
    { title: "Behind the Lens — A Day in My Studio", likes: 42100, comments: 2340, thumbnail: "https://picsum.photos/seed/42/400/300", engagement: 16.2 },
    { title: "Controversial Take on Content Burnout", likes: 38900, comments: 3100, thumbnail: "https://picsum.photos/seed/77/400/300", engagement: 14.9 },
    { title: "5 AI Tools I Use Every Day", likes: 31200, comments: 1890, thumbnail: "https://picsum.photos/seed/23/400/300", engagement: 12.1 },
    { title: "How I Got My First Brand Deal", likes: 29400, comments: 2200, thumbnail: "https://picsum.photos/seed/88/400/300", engagement: 11.5 },
    { title: "Morning Routine of a 6-Figure Creator", likes: 24600, comments: 1650, thumbnail: "https://picsum.photos/seed/55/400/300", engagement: 9.8 },
  ],
  growth_data: Array.from({ length: 24 }, (_, i) => {
    const base = 210000;
    const w = Math.floor(i);
    const date = new Date(Date.now() - (24 - i) * 7 * 24 * 60 * 60 * 1000);
    return {
      week: date.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
      followers: Math.round(base + (base * 0.36 * (i / 24)) + Math.random() * 3000),
      engagement: +(3.2 + Math.random() * 4.5).toFixed(1),
      views: Math.round(40000 + Math.random() * 120000),
    };
  }),
};

export const TESTIMONIALS = [
  { name: "Priya Sharma", handle: "@priya.creates", avatar: "PS", text: "AstroForge AI completely changed how I approach content. The AI insights were brutally accurate — it called out exactly what I was doing wrong and my views tripled in 6 weeks.", followers: "127K", platform: "Instagram", stars: 5 },
  { name: "Marcus Wei", handle: "@marcus.builds", avatar: "MW", text: "The astrology section sounds wild but the posting time recommendations actually work. I moved my posts to the suggested windows and my reach jumped 240%. I'm a believer.", followers: "89K", platform: "YouTube", stars: 5 },
  { name: "Sofia Reyes", handle: "@sofia.travels", avatar: "SR", text: "The goal planner showed me my 500K target was achievable in 8 months if I post 5x/week. Now at month 4 and I'm ahead of schedule. The daily action plan is gold.", followers: "312K", platform: "TikTok", stars: 5 },
  { name: "Arjun Mehta", handle: "@arjun.digital", avatar: "AM", text: "Most analytics tools give you data with no direction. This platform gives you the brutally honest truth + a clear path forward. The hook ideas alone are worth 10x the price.", followers: "44K", platform: "Instagram", stars: 5 },
];

export const MOCK_INSIGHTS = {
  profile_analysis: "Your Instagram presence at 284K is genuinely impressive, but you're leaving serious money and reach on the table. Your engagement rate of 4.8% puts you in the top 15% of creators globally — yet your growth has plateaued at roughly 3% monthly. The audience trusts you; you just need to stop playing it safe.",
  mistakes: [
    "Posting at inconsistent times — your audience never knows when to expect you",
    "Captions are informative but lack emotional triggers that drive saves & shares",
    "Not using Collab posts — you're missing free exposure to partner audiences",
    "Reels under 30s are underperforming; the algorithm rewards 45-90s right now",
    "Zero long-form content — YouTube Shorts pipeline would 3x your discovery",
  ],
  daily_plan: [
    "8:00 AM — Review yesterday's analytics, note top-performing post",
    "9:00 AM — Film 2 Reels (one trend-based, one niche-expertise)",
    "11:00 AM — Edit, caption with 3-5 keyword-rich sentences + CTA",
    "1:00 PM — Comment on 20 posts from niche accounts (genuine engagement)",
    "3:00 PM — Schedule post for 6 PM peak window",
    "7:00 PM — Reply to ALL comments within 90 min of posting",
  ],
  content_ideas: [
    "\"What 5 years of content creation actually taught me\" — raw & honest",
    "React to the worst content advice on the internet",
    "Week in my life earning $X from content (specific number = viral)",
    "The equipment setup nobody told you about when starting out",
    "I analyzed 100 viral posts — here's the pattern nobody talks about",
    "Storytime: The brand deal that almost ruined my reputation",
    "A-B test: Same post, different hook — results shocked me",
    "Debunking the top 7 growth myths in your niche",
    "The unsent DMs — what brands say about creators behind closed doors",
    "24-hour content sprint: making 30 pieces of content in one day",
  ],
  hook_ideas: [
    "Nobody tells you THIS when you hit 100K — I wish someone had",
    "I spent $10,000 on a course so you don't have to. Here's the truth.",
    "The algorithm is literally broken right now. Here's how to exploit it.",
    "Stop making content. Seriously. Until you watch this.",
    "I interviewed 50 creators who grew from 0 to 100K in 90 days. Here's what every single one said.",
    "POV: You finally understand why your content isn't growing",
    "This one mindset shift doubled my views in 2 weeks",
    "Brutally honest: Your content isn't bad, your hook is",
    "What 10 million views looks like on your analytics (and bank account)",
    "I'm about to say something controversial about content creation…",
  ],
  posting_schedule: {
    Monday: ["10:00 AM", "7:00 PM"],
    Tuesday: ["12:00 PM"],
    Wednesday: ["9:00 AM", "6:30 PM"],
    Thursday: ["11:00 AM"],
    Friday: ["10:00 AM", "8:00 PM"],
    Saturday: ["2:00 PM", "7:00 PM"],
    Sunday: ["5:00 PM"],
  },
  growth_prediction: {
    month_1: 302000,
    month_3: 348000,
    month_6: 432000,
    month_12: 680000,
    confidence: "medium",
  },
  feasibility_score: 78,
};

export const MOCK_ASTROLOGY = {
  sun_sign: "Aquarius",
  personality_insights: "As an Aquarius creator, you carry an innate ability to see trends 6 months before they hit mainstream — this is your unfair advantage. Your birth chart reveals a rare Mercury-Jupiter alignment that amplifies communication magnetism. Audiences unconsciously feel your authenticity and future-forward energy before they even process your content.",
  growth_patterns: "Your growth pattern follows a distinctive wave cycle: 6-8 weeks of steady gains followed by a viral breakthrough moment. The stars indicate a major inflection point approaching in the next 45-60 days. Saturn's current positioning rewards creators who show up consistently even when it feels pointless.",
  lucky_posting_times: ["8:00–10:00 AM (Jupiter hour)", "12:00–2:00 PM (Sun hour)", "6:30–9:00 PM (Venus hour)"],
  strengths: ["Visionary thinking that creates paradigm-shifting content", "Deep audience intuition — you know what they want before they do", "Resilience during algorithm changes that breaks other creators", "Natural collaborator energy that attracts high-value partnerships"],
  weaknesses: ["Overthinking content until the moment passes", "Mercury retrograde periods hit you harder than most", "Tendency to pivot strategy too frequently before seeing results"],
  best_content_types: ["Future predictions & trend forecasting", "Tech & AI integration tutorials", "Philosophical deep-dives with practical application"],
  monthly_forecast: "This lunar cycle strongly favors Aquarius creators in the digital space. The Jupiter-Venus trine on the 18th creates peak audience receptivity — plan your most important launch or post for this window. Avoid major pivots during the new moon phase; consolidate instead.",
};

export const GOAL_PROJECTION = Array.from({ length: 13 }, (_, i) => ({
  month: i,
  followers: Math.round(284700 * Math.pow(1.065, i)),
  target: Math.round(284700 + (215300 * i / 12)),
}));